### ISSUE TITLE
Unknown error when starting email gen

### ISSUE THREAD

**Issue by independence106** [david96182/ninjemail#19]
Heres my code:
from ninjemail import Ninjemail
```
# Replace "YOUR_API_KEY", "USERNAME" and "TOKEN" with your actual keys
if __name__ == '__main__':
	ninja = Ninjemail(
				browser="chrome",
				captcha_keys={"nopecha": "(key lol)"},
				auto_proxy=True)
	email, password = ninja.create_outlook_account(
							username="testuser", 
							password="testpassword", 
							first_name="John", 
							last_name="Doe", 
							country="USA", 
							birthdate="01-01-1990"
	)

	print(f"Email: {email}")
	print(f"Password: {password}")
```

Here's the error.
Traceback (most recent call last):
  File "C:\Users\indep\ninjemail\script.py", line 9, in <module>
    email, password = ninja.create_outlook_account(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indep\ninjemail\ninjemail\ninjemail_manager.py", line 177, in create_outlook_account
    driver = create_driver(self.browser, captcha_extension=True, proxy=proxy, captcha_key=captcha_key)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\indep\ninjemail\ninjemail\utils\webdriver_utils.py", line 172, in create_driver
    driver.get(f"https://nopecha.com/setup#{captcha_key.get('key', None)}")
  File "C:\Users\indep\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\webdriver.py", line 363, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\indep\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\indep\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response        
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_TUNNEL_CONNECTION_FAILED
  (Session info: chrome=130.0.6723.70)
Stacktrace:

**Comment by david96182** [comment]
Hi, the error indicates that there is a connection issue. You used the auto_proxy feature, which gets free proxies that are not always reliable and can cause these kinds of errors. My recommendation to get the best results is to always use your own proxies.
