### ISSUE TITLE
NoSuchElementException in month_combobox selection for Gmail

### ISSUE THREAD

**Issue by elcoloo** [david96182/ninjemail#6]
I got this error:

```
(env2) colo@vm-ubuntudesk:~/ninjemail$ python gmail.py
Traceback (most recent call last):
  File "/home/colo/ninjemail/gmail.py", line 9, in <module>
    email, password = ninja.create_gmail_account(
  File "/home/colo/ninjemail/ninjemail/ninjemail_manager.py", line 228, in create_gmail_account
    return gmail.create_account(driver,
  File "/home/colo/ninjemail/ninjemail/email_providers/gmail.py", line 76, in create_account
    month_combobox.select_by_index(month)
  File "/home/colo/env2/lib/python3.10/site-packages/selenium/webdriver/support/select.py", line 100, in select_by_index
    raise NoSuchElementException(f"Could not locate element with index {index}")
selenium.common.exceptions.NoSuchElementException: Message: Could not locate element with index 09; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
```

**Comment by david96182** [comment]
Thanks for reporting the error. I'm not sure if the error could be related to a bad connection, bad proxies, or if Gmail changes HTML classes and structure sometimes but not always. If you have any other details that could help debug this, please share them.

**Comment by david96182** [comment]
I noticed that the month selection in Gmail was using the value as it came. I've updated it to use the integer value of the month. Please test it and let me know if this resolves your issue.
